name: Update Config Files

on:
  push:
    branches:
      - main
      - test
      - dev
    paths:
      - 'homer/homer-prod-1/config/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: "self-hosted"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload new Config Files
        uses: appleboy/scp-action@master
        with:
          username: xcad
          host: nas-prod-1.home.clcreative.de
          key: ${{ secrets.SSH_XCAD }}
          source: './homer/homer-prod-1/config/*'
          target: '/mnt/store/app-pv/homer-prod-1-vol-1'
          strip_components: 3
          overwrite: true
